### ISSUE TITLE
Bot does not respond

### ISSUE THREAD

**Issue by asdfghjaz** [Voxter256/Secret-Santa-Bot#3]
There are times when the bot does not respond or reply. This happens in both private message and group chat. When the bot does reply, it happens a day later. Any insight on why this is happening?

**Comment by Voxter256** [comment]
Hey @asdfghjaz ,
I'm terribly sorry about that. If the bot is ever not responding, feel free to message me directly on Telegram at [https://t.me/Voxter256](https://t.me/Voxter256)

Generally speaking, that happens when the bot goes offline for whatever reason (the last one was automatic windows updates I didn't expect). Telegram puts all of the messages in a queue until the bot comes back online, at which point they are all sent out. 

I had originally planned to solve this by hosting it on AWS, but that turned out to be too expensive for the relatively low amount of traffic. (The bot sends some messages that aren't a direct response to another. Because of this and the need for a database, a NAT Gateway needs to be setup to allow communication outside of the VPC the database is in. Unfortunately it is priced for every hour it is provisioned and available, which came out to ~ $30 a month.)

I am currently brainstorming some long term solutions, such as a small raspberry pi cluster hosting Kubernetes, but that likely won't be up until next year's Holiday season.
